### ISSUE TITLE
AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'

### ISSUE THREAD

**Issue by sarahshuang** [chenhcs/SCS#16]
Hi,

I am running <patch_cut.py>, but encounted with the following error. 
`AttributeError: module 'matplotlib.pyplot' has no attribute 'register_cmap'`

The recommended version of matplotlib is 3.5.0, while the version here is 3.9.1. Could it be the reason for the error? Could you please give me some suggestions? Thank you!

**Comment by Yifan-debug** [comment]
The same error code here. I tried to import the spateo, and it said the  module 'matplotlib.pyplot' has no attribute 'register_cmap'

**Comment by Yifan-debug** [comment]
I installed matplotlib==3.5.1. and it works for me. I'm not sure if this will help you.

**Comment by sarahshuang** [comment]
> I installed matplotlib==3.5.1. and it works for me. I'm not sure if this will help you.

Thank you! It works for me as well.
